cfg:
  checkpoint_path: /home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/crash_tests/empty_nodes/sigma_100
  classifier_checkpoint_path: /home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/lightning_logs/classifier/version_71
  explain_sample_idx: 5
  extracted_embeddings_path: /home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/data/embeddings/minnie65_embeddings.pt
  folder_to_label:
    ab: 0
    wt: 1
  learning_rate: 0.001
  max_epochs: 1000
  noise_sigma: 0
  num_classes: 2
  optimizer:
    _target_: torch.optim.AdamW
    weight_decay: 1.0e-05
  path: /home/eugen/Desktop/CodeWork/Projects/Diplom/Archiv/processed_dataset
  pooling_level: neuron
  pooling_type: add
  scheduler:
    T_max: 1000
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  sigma: 1.0
  stats_path: /home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/data/stats_9009_sph/
  weight_decay: 1.0e-05
learning_rate: 0.001
