import torch.nn as nn
from torch_geometric.nn import radius_graph
from src.data_utils.structural_stats import ThesisMacroMetrics
from pathlib import Path
from tqdm import tqdm
from omegaconf import DictConfig
from ..data_utils.stats import load_stats
import torch
from torch_geometric.data import Data
from torch_geometric.utils import subgraph

def fast_normalization_by_features(data, eps=1e-6):
    """
    Считает среднее и std для каждого из 21 признака, 
    игнорируя значения |x| <= eps.
    """
    mask = data.abs() > eps
    means = torch.zeros(data.size(1))
    stds = torch.ones(data.size(1))
    
    for i in range(data.size(1)):
        col = data[:, i]
        col_mask = mask[:, i]
        
        if torch.any(col_mask):
            valid_data = col[col_mask]
            means[i] = valid_data.mean()
            stds[i] = valid_data.std() if valid_data.numel() > 1 else 1.0
        else:
            means[i] = 0.0
            stds[i] = 1.0
            
    return means, stds



def create_mask_collate_fn(transform: 'GenNormalize' = None):
    from torch_geometric.data import Batch
    
    def mask_collate_fn(batch):
        if transform is None:
            return Batch.from_data_list(batch)
        
        contexts = []
        targets = []
        
        for data in batch:
            
            ctx, tgt = transform(data)
            if ctx.num_nodes > 0 and tgt.num_nodes > 0:
                contexts.append(ctx)
                targets.append(tgt)

        
        if len(contexts) == 0:
            return None
        
        context_batch = Batch.from_data_list(contexts)
        target_batch = Batch.from_data_list(targets)
        
        return context_batch, target_batch
    
    return mask_collate_fn



        

class NormNoEps(torch.nn.Module):
    def __init__(self, mean : torch.Tensor , std : torch.Tensor , eps: float = 0.0):
        super().__init__()
        self.register_buffer("mean", mean)
        self.register_buffer("std", std)
        if torch.any(std.abs() < 1e-8):
            raise ValueError("Your std is too small. It's dangerous for division!")
        self.eps = eps
    def forward(self,data) -> torch.Tensor:
        mask = (data.x.abs() > self.eps)
        normalized_x  = (data.x - (self.mean))/(self.std)
        data.x = torch.where(mask,normalized_x,data.x)
        return data
    

class EdgeNorm(torch.nn.Module):
    def __init__(self, mean : torch.Tensor , std: torch.Tensor):
        super().__init__()
        self.register_buffer("mean", mean)
        self.register_buffer("std", std)
        if torch.any(std.abs() < 1e-8):
            raise ValueError("Your std is too small. It's dangerous for division!")
    def forward(self, data):
        data.edge_attr = (data.edge_attr - self.mean)/self.std
        return data
        
class LocalPos(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self,data):
        pos = data.pos
        pos_mean = torch.mean(pos,dim=0)
        pos_std = torch.std(pos,dim=0).clamp(min=1e-6)
        pos = (pos - pos_mean)/pos_std
        data.pos = pos
        return data





class GraphPruning(torch.nn.Module):
    '''
    Return graph generated by radius, replacing original edge_index.
    '''
    def __init__(self, r=-1.0):
        super().__init__()
        self.r = r
        
    def forward(self, data):
        if self.r < 0.0:
            return data

        new_edge_index = radius_graph(
            data.pos,
            r=self.r,
            batch=data.batch,
            loop=False,
            max_num_neighbors=data.num_nodes
        )
        row, col = new_edge_index
        dists = (data.pos[row] - data.pos[col]).norm(dim=-1, keepdim=True)
        data.edge_index = new_edge_index
        data.edge_attr = dists

        return data





class MaskData(torch.nn.Module):
    '''
    Waring! This class return TWO graphs , contex and target (In JEPA notations)

    '''
    def __init__(self, mask_ratio: float):
        super().__init__()
        self.mask_ratio = mask_ratio

    def _get_random_node_mask(self, data: Data) -> torch.Tensor:
        """Uniform random node masking without topological constraints."""
        num_nodes = data.num_nodes
        num_mask_goal = max(1, int(num_nodes * self.mask_ratio))
        
        device = data.x.device if hasattr(data, 'x') and data.x is not None else 'cpu'
        mask = torch.zeros(num_nodes, dtype=torch.bool, device=device)
        
        perm = torch.randperm(num_nodes, device=device)
        selected = perm[:num_mask_goal]
        
        mask[selected] = True
        
        return mask

    def _split_data_by_mask(self, data, mask):
        num_nodes = data.num_nodes
        if mask.sum() == 0:
            mask[torch.randint(0, num_nodes, (1,)).item()] = True
        if (~mask).sum() == 0:
            true_idx = mask.nonzero(as_tuple=True)[0][0].item()
            mask[true_idx] = False
        
        subset_ctx = ~mask
        subset_tgt = mask
        def build_subgraph(subset):
            edge_index, edge_attr = subgraph(
                subset, data.edge_index, edge_attr=data.edge_attr, 
                relabel_nodes=True, num_nodes=data.num_nodes
            )
            
            return Data(
                x=data.x[subset],
                pos=data.pos[subset] if data.pos is not None else None,
                edge_index=edge_index,
                edge_attr=edge_attr,
                y=data.y if hasattr(data, 'y') and data.y is not None else None,
                segment_id=data.segment_id if hasattr(data, 'segment_id') else None,
            )

        return build_subgraph(subset_ctx), build_subgraph(subset_tgt)

    def forward(self, data):
        mask = self._get_random_node_mask(data)
        return self._split_data_by_mask(data, mask)
class FeatureChoice(nn.Module):
    '''
    Input list of index of choiced feature for training
    '''
    def __init__(self, feature = None):
        super().__init__()
        self.feature = feature
    def forward(self, data):
        if self.feature is not None:
            data.x = data.x[:, self.feature]
        return data



class GenNormalize(torch.nn.Module):
    def __init__(self, transforms, mask_transform = None):
        super().__init__()
        self.transforms = transforms
        self.mask_transform = mask_transform
    def forward(self, data):
        out = data
        for transform in self.transforms:
            out = transform(out)
        if self.mask_transform is not None:
            context, target = self.mask_transform(out)
            return context, target
        return out


class ConcatStructuralPE(torch.nn.Module):
    """
    Конкатенирует предварительно рассчитанные структурные фичи
    (Laplacian, Centrality, RandomWalk) к data.x
    без их перевычисления.
    """
    def __init__(self):
        super().__init__()

    def forward(self, data):
        pe_list = []
        if hasattr(data , 'laplacian_pe') and data.laplacian_pe is not None:
            pe_list.append(data.laplacian_pe.to(data.x.device))
        if hasattr(data , 'centrality_pe') and data.centrality_pe is not None:
            pe_list.append(data.centrality_pe.to(data.x.device))
        if hasattr(data , 'random_walk_pe') and data.random_walk_pe is not None:  
            pe_list.append(data.random_walk_pe.to(data.x.device))
            
        if len(pe_list) > 0:
            pe_tensor = torch.cat(pe_list, dim=1)
            data.x = torch.cat([data.x, pe_tensor], dim=1)
            
        return data


class FeatureShuffling(torch.nn.Module):
    """
    Shuffles node features (data.x) with a given ratio.
    ratio = 0: No shuffling (original graph)
    ratio = 1: Absolute random shuffling (no attention to structure)
    0 < ratio < 1: Partial shuffling (spectrum of randomness)
    """
    def __init__(self, ratio: float = 0.0):
        super().__init__()
        self.ratio = ratio

    def forward(self, data):
        if self.ratio <= 0:
            return data
        
        num_nodes = data.x.size(0)
        if num_nodes <= 1:
            return data
            
        if self.ratio >= 1.0:
            # Full random permutation
            perm = torch.randperm(num_nodes, device=data.x.device)
            data.x = data.x[perm]
        else:
            num_to_shuffle = int(num_nodes * self.ratio)
            if num_to_shuffle > 1:
                indices = torch.randperm(num_nodes, device=data.x.device)[:num_to_shuffle]
                shuffled_indices = indices[torch.randperm(num_to_shuffle, device=data.x.device)]
                data.x[indices] = data.x[shuffled_indices].clone()
        
        return data


class GaussianNoiseAugmentation(torch.nn.Module):
    """
    Adds Gaussian noise N(0, sigma) to node features.
    sigma = 0: no noise (original features preserved)
    sigma > 0: data.x = data.x + N(0, sigma)
    """
    def __init__(self, sigma: float = 0.0):
        super().__init__()
        self.sigma = sigma

    def forward(self, data):
        if self.sigma > 0:
            noise = torch.randn_like(data.x) * self.sigma
            data.x = data.x + noise
        return data


class GaussianPositionNoise(torch.nn.Module):
    """
    Adds Gaussian noise N(0, sigma) to node positions.
    sigma = 0: no noise (original positions preserved)
    sigma > 0: data.pos = data.pos + N(0, sigma)
    """
    def __init__(self, sigma: float = 0.0):
        super().__init__()
        self.sigma = sigma

    def forward(self, data):
        if self.sigma > 0 and data.pos is not None:
            noise = torch.randn_like(data.pos) * self.sigma
            data.pos = data.pos + noise
        return data


def build_transforms(cfg, mean_x, std_x, mean_edge, std_edge):
    """
    Build transforms config.
    """
    transforms = []
    
    features = cfg.get('features', None)
    if features is not None:
        features = list(features)
        transforms.append(FeatureChoice(feature=features))
        mean_x = mean_x[features]
        std_x = std_x[features]
    
    transforms.append(NormNoEps(mean=mean_x, std=std_x, eps=cfg.get('eps', 1e-6)))
    transforms.append(LocalPos())
    radius_r = cfg['r']
    transforms.append(GraphPruning(r=radius_r))
    transforms.append(ThesisMacroMetrics())
    transforms.append(ConcatStructuralPE())
    
    return transforms






def preprocess_dataset(cfg: DictConfig, input_path: Path, output_path: Path) -> None:
    """
    Предобрабатывает датасет и сохраняет результат.

    Args:
        cfg:         конфиг секции datamodule
        input_path:  папка с исходными .pt файлами
        output_path: папка для сохранения предобработанных файлов
    """
    file_paths = sorted(input_path.rglob("*.pt"))
    print(f"Preparing {len(file_paths)} files from {input_path}...")
    print(f"Saving pre-processed dataset to: {output_path}")
    mean_x, std_x, mean_edge, std_edge = load_stats(cfg.dataset.stats_path)
    

    transforms = build_transforms(cfg, mean_x, std_x, mean_edge, std_edge)
    static_transform = GenNormalize(transforms=transforms, mask_transform=None)

    for file_path in tqdm(file_paths):
        data = torch.load(file_path, map_location="cpu", weights_only=False)
        data = static_transform(data)

        out_file = output_path / file_path.relative_to(input_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)
        torch.save(data, out_file)

    print(f"Done! Update config 'dataset.path' to: {output_path}")

import hydra
@hydra.main(version_base="1.3", config_path="../../configs", config_name="config")
def main(cfg: DictConfig):
    preprocess_dataset(cfg.datamodule,Path("datasets/dataset_sph_minnie65"),Path("datasets/dataset_sph_minnie65_r=1.5") )

if __name__ == "__main__":
    main()