seed: 51

# Network configuration
network:
  _target_: src.models.jepa.LeJEPA
  encoder:
    _target_: src.models.encoder.GraphGinEncoder
    in_channels: 100  # Base 21 + Laplacian 4 + Centrality 1 + RW 5 = 31
    out_channels: 32
    num_layers: 3
  predictor:
    _target_: src.models.jepa.CrossAttentionPredictor
    hidden_dim: 32
    pos_dim: 3
    num_heads: 2
    dropout: 0.05
  lambd: 0.01
  num_slices: 32
  ema: 0.996
  

# Training configuration
training:
  learning_rate: 1e-2
  weight_decay: 1e-5
  max_epochs: 200
  optimizer:
    _target_: torch.optim.AdamW
    weight_decay: ${training.weight_decay}
  scheduler:    # Для соотвествия с экспериментом
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: ${training.max_epochs}

# Trainer configuration
trainer:
  max_epochs: ${training.max_epochs}
  accelerator: "gpu"
  devices: 1
  log_every_n_steps: 10
  

# DataModule configuration
datamodule:
  _target_: src.data_utils.datamodule.GraphDataModule
  dataset:
    _target_: src.data_utils.datamodule.GraphDataSet
    path: "/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/datasets/dataset_prepared"
    raw_path: "/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/datasets/dataset_sph_minnie65"
    stats_path: '/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/data/stats_sph/'
    class_path: '/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/public_cave_ground_truth_cell_types_with_nucleus.csv'
  #features: [0,4,5,6,7,13,14,15,17,19,20]
  batch_size: 1024
  num_workers: 2
  r: 6
  mask_ratio: 0.05
  structural_encoding:
    laplacian_k: 0     # 4 features
    centrality: false     # 1 feature
    random_walk_steps: 0  # 5 features
  seed: ${seed}

  ratio: [0.8,0,0.2]


representation:
  enabled: true
  batch_size: 2
  datasets:
    - path: "/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/notebooks/graph_dataset_output_ab"
      label: 0
    - path: "/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/notebooks/graph_dataset_output_wt"
      label: 1
  # Доступные эстиматоры: rank_me, isotropy, uniformity, cluster, recall, alignment
  #features: [0,4,5,6,7,13,14,15,17,19,20]
  estimators:
    - rank_me
    - isotropy
    - uniformity

  stats_path: "/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/data/stats_9009/"
  r: 0.00001
  structural_encoding:
    laplacian_k: 4
    centrality: true
    random_walk_steps: 5

# Classifier training (linear probe on frozen JEPA encoder)
classifier:
  pca_components: 20
  checkpoint_path: '/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/lightning_logs/jepa_r_1.5_sh_1.0/version_0'
  classifier_checkpoint_path: '/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/lightning_logs/classifier/version_71'
  path: "/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/datasets/dataset_prepared"
  stats_path: "/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/data/stats_sph/"
  num_classes: 11
  folder_to_label:
    ab: 0
    wt: 1
  learning_rate: 1e-3
  weight_decay: 1e-5
  max_epochs: 3000
  optimizer:
    _target_: torch.optim.AdamW
    weight_decay: ${classifier.weight_decay}
  scheduler: 
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: ${classifier.max_epochs}

  sigma: 1.0
  explain_sample_idx: 5
  extracted_embeddings_path: "/home/eugen/Desktop/CodeWork/Projects/Diplom/notebooks/GIT_Graph_refactor/data/embeddings/minnie65_embeddings.pt"
  pooling_level: "neuron"  # 'graph' or 'neuron'
  pooling_type: "add"     # 'mean' or 'add'
